-- Написать DML-триггер, регистрирующий изменение данных (вставку, обновление, удаление) в одной из таблиц БД.
-- Во вспомогательную таблицу LOG1 записывать, кто, когда (дата и время) и какое именно изменение произвел,
-- для одного из столбцов сохранять старые и новые значения писать DML-триггер, регистрирующий изменение
-- данных (вставку, обновление, удаление) в одной из таблиц БД. Во вспомогательную таблицу LOG1 записывать,
-- кто, когда (дата и время) и какое именно изменение произвел, для одного из столбцов сохранять старые и новые значения.

CREATE TABLE LOG1
(
    id          INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR2(50),
    operation   VARCHAR2(10),
    user_name   VARCHAR2(50),
    change_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    column_name VARCHAR2(50),
    old_value   VARCHAR2(4000),
    new_value   VARCHAR2(4000)
);

CREATE OR REPLACE TRIGGER trg_contract_log
    AFTER INSERT OR UPDATE OR DELETE
    ON insurance_contract
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO LOG1(table_name, operation, user_name, column_name, new_value)
        VALUES ('INSURANCE_CONTRACT', 'INSERT', USER, 'CONTRACT_STATUS', :NEW.contract_status);
    ELSIF UPDATING THEN
        INSERT INTO LOG1(table_name, operation, user_name, column_name, old_value, new_value)
        VALUES ('INSURANCE_CONTRACT', 'UPDATE', USER, 'CONTRACT_STATUS', :OLD.contract_status, :NEW.contract_status);
    ELSIF DELETING THEN
        INSERT INTO LOG1(table_name, operation, user_name, column_name, old_value)
        VALUES ('INSURANCE_CONTRACT', 'DELETE', USER, 'CONTRACT_STATUS', :OLD.contract_status);
    END IF;
END;
/

-- Проверка INSERT
INSERT INTO insurance_contract (id, contract_date, contract_status, payout_deadline, agent_id, client_id, insurance_type_id, premium, unpaid_premium)
VALUES (1000, SYSDATE, 'Активен', 30, 1, 1, 1, 1000, 0);

-- Проверка UPDATE
UPDATE insurance_contract SET contract_status = 'Завершён' WHERE id = 1000;

-- Проверка DELETE
DELETE FROM insurance_contract WHERE id = 1000;


-- Написать DDL-триггер, протоколирующий действия пользователей по
-- созданию, изменению и удалению таблиц в схеме во вспомогательную таблицу
-- LOG2 в определенное время и запрещающий эти действия в другое время.
CREATE TABLE LOG2
(
    id          INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_name   VARCHAR2(50),
    operation   VARCHAR2(30),
    object_name VARCHAR2(100),
    log_date    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_ddl_log
    AFTER CREATE OR ALTER OR DROP
    ON SCHEMA
DECLARE
    v_hour NUMBER := TO_NUMBER(TO_CHAR(SYSTIMESTAMP AT TIME ZONE 'Europe/Moscow', 'HH24'));
BEGIN
    IF v_hour BETWEEN 9 AND 24 THEN
        INSERT INTO LOG2(user_name, operation, object_name)
        VALUES (SYS_CONTEXT('USERENV', 'SESSION_USER'), ORA_SYSEVENT, ORA_DICT_OBJ_NAME);
    ELSE
        RAISE_APPLICATION_ERROR(-20030, 'DDL-операции разрешены только с 9 до 17');
    END IF;
END;
/

-- Для теста
CREATE TABLE test_tbl (
id NUMBER
);

-- меняем структуру
ALTER TABLE test_tbl ADD name VARCHAR2(100);

-- удаляем
DROP TABLE test_tbl;

-- Написать системный триггер, добавляющий запись во вспомогательную
-- таблицу LOG3, когда пользователь подключается или отключается. В таблицу
-- логов записывается имя пользователя (USER), тип активности (LOGON или LOGOFF),
-- дата (SYSDATE), количество записей в основной таблице БД.

CREATE TABLE LOG3
(
    id           INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_name    VARCHAR2(50),
    activity     VARCHAR2(10),
    log_date     TIMESTAMP DEFAULT SYSTIMESTAMP,
    contract_cnt NUMBER
);

CREATE OR REPLACE TRIGGER trg_logon
    AFTER LOGON
    ON DATABASE
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM insurance_contract;
    INSERT INTO EVLAD.LOG3(user_name, activity, contract_cnt)
    VALUES (USER, 'LOGON', v_cnt);
END;
/

CREATE OR REPLACE TRIGGER trg_logoff
    BEFORE LOGOFF
    ON DATABASE
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM insurance_contract;
    INSERT INTO EVLAD.LOG3(user_name, activity, contract_cnt)
    VALUES (USER, 'LOGOFF', v_cnt);
END;
/

-- Написать триггеры, реализующие бизнес-логику (ограничения) в задан-ной
-- вариантом предметной области. Три задания приведены в прил. 6. Количество
-- и тип триггеров (строковый или операторный, выполняется AFTER или BEFORE)
-- определять самостоятельно исходя из сути заданий и имеющейся схемы БД; учесть,
-- что в некоторых вариантах первые два задания могут быть выполнены в рамках одного триггера,
-- а также возможно возникновение мутации, что приведет к совмещению данного пункта
-- лабораторной работы со сле-дующим. Третий пункт задания предполагает использование
-- планировщика задач, который обязательно должен быть настроен на многократный запуск
-- с использованием частоты, интервала и спецификаторов.

-- 1)При заполнении информации о договоре автоматически вносить текущую дату как начальную, если она не указана агентом,
-- и дату окончания страховки в зависимости от типа и срока страхования, рассчитывать общую стоимость и первоначальный взнос.
-- 2)Следить за суммами выплат, начислять пеню за просроченные выплаты.
-- 3)Переносить в архив старые договора, указывая сумму страховки и выплаты по страховым случаям, если они были.

-- При заполнении информации о договоре автоматически вносить текущую дату как начальную, если она не указана агентом,
-- и дату окончания страховки в зависимости от типа и срока страхования, рассчитывать общую стоимость и первоначальный взнос.
ALTER TABLE insurance_contract
    ADD (
        end_date DATE,
        initial_payment NUMERIC(15, 2)
        );

CREATE OR REPLACE TRIGGER trg_contract_defaults
    BEFORE INSERT
    ON insurance_contract
    FOR EACH ROW
DECLARE
    v_type_name insurance_type.name%TYPE;
    v_coef      NUMBER := 1;
BEGIN
    IF :NEW.contract_date IS NULL THEN
        :NEW.contract_date := SYSDATE;
    END IF;

    :NEW.end_date := :NEW.contract_date + NVL(:NEW.payout_deadline, 365);

    SELECT name
    INTO v_type_name
    FROM insurance_type
    WHERE id = :NEW.insurance_type_id;

    IF v_type_name = 'Жизнь' THEN
        v_coef := 1.5;
    ELSIF v_type_name = 'Авто' THEN
        v_coef := 1.2;
    ELSIF v_type_name = 'Жилье' THEN
        v_coef := 1.3;
    ELSE
        v_coef := 1;
    END IF;

    :NEW.premium := :NEW.premium * v_coef;
    :NEW.initial_payment := :NEW.premium * 0.2;

END;
/

-- INSERT INTO insurance_contract (contract_date, contract_status, payout_deadline, agent_id, client_id, insurance_type_id, premium, unpaid_premium) VALUES (DATE '2024-03-25', 'Активен', 30, 1, 1, 1, 1200.00, 0.00);


-- 2)Следить за суммами выплат, начислять пеню за просроченные выплаты.
ALTER TABLE payment
    ADD penalty NUMERIC(15, 2);

CREATE OR REPLACE TRIGGER trg_payment_penalty
    BEFORE INSERT OR UPDATE
    ON payment
    FOR EACH ROW
DECLARE
    v_deadline DATE;
BEGIN
    SELECT c.contract_date + c.payout_deadline
    INTO v_deadline
    FROM insurance_contract c
    WHERE c.id = :NEW.insurance_contract_id;

    IF :NEW.payment_date > v_deadline THEN
        :NEW.penalty := (:NEW.amount * 0.01) * (TRUNC(:NEW.payment_date - v_deadline));
    ELSE
        :NEW.penalty := 0;
    END IF;
END;
/

INSERT INTO payment (insurance_contract_id, amount, payment_date)
VALUES (2, 2000, SYSDATE + 400);

-- 3)Переносить в архив старые договора, указывая сумму страховки и выплаты по страховым случаям, если они были.
CREATE TABLE insurance_contract_archive AS
SELECT *
FROM insurance_contract
WHERE 1 = 0;

ALTER TABLE insurance_contract_archive
    ADD (
        total_payout NUMERIC(15, 2)
        );

CREATE OR REPLACE TRIGGER trg_contract_archive
    FOR UPDATE OF contract_status
    ON EVLAD.insurance_contract
    COMPOUND TRIGGER
    TYPE t_contract_ids IS TABLE OF EVLAD.insurance_contract.id%TYPE;
    g_ids t_contract_ids := t_contract_ids();

AFTER EACH ROW IS
BEGIN
    IF :NEW.contract_status = 'Завершён' THEN
        g_ids.EXTEND;
        g_ids(g_ids.LAST) := :NEW.id;
    END IF;
END AFTER EACH ROW;

    AFTER STATEMENT IS
    BEGIN
        FOR i IN 1 .. g_ids.COUNT
            LOOP
                DECLARE
                    v_total_payout NUMBER;
                BEGIN
                    SELECT NVL(SUM(cc.approved_amount), 0)
                    INTO v_total_payout
                    FROM EVLAD.compensation_claim cc
                    WHERE cc.insurance_contract_id = g_ids(i);

                    INSERT INTO EVLAD.insurance_contract_archive
                    SELECT c.*, v_total_payout
                    FROM EVLAD.insurance_contract c
                    WHERE c.id = g_ids(i);

                    DELETE
                    FROM EVLAD.payment
                    WHERE insurance_contract_id = g_ids(i);
                    DELETE
                    FROM EVLAD.compensation_claim
                    WHERE insurance_contract_id = g_ids(i);
                    DELETE FROM EVLAD.insurance_contract WHERE id = g_ids(i);
                END;
            END LOOP;
    END AFTER STATEMENT;
    END trg_contract_archive;
/


CREATE OR REPLACE PROCEDURE proc_check_and_archive IS
BEGIN
    UPDATE EVLAD.insurance_contract
    SET contract_status = 'Завершён'
    WHERE contract_status = 'Завершён';

    COMMIT;
END;
/

BEGIN
    DBMS_SCHEDULER.create_job(
            job_name => 'JOB_TRIGGER_ARCHIVE',
            job_type => 'STORED_PROCEDURE',
            job_action => 'PROC_CHECK_AND_ARCHIVE',
            start_date => SYSTIMESTAMP,
            repeat_interval => 'FREQ=MINUTELY; INTERVAL=1',
            enabled => TRUE
    );
END;
/

SELECT job_name, enabled, state, repeat_interval, last_start_date, next_run_date
FROM user_scheduler_jobs
WHERE job_name = 'JOB_TRIGGER_ARCHIVE';



UPDATE insurance_contract
SET contract_status = 'Завершён'
WHERE id = 1;

-- Самостоятельно или при помощи преподавателя составить задание на
-- DML триггер, который будет вызывать мутацию таблицы, на которую создан,
-- в случае присутствия в теле триггера команды записи (INSERT INTO, UPDATE, DELETE)
-- в ту же таблицу, и решить эту проблему одним из двух способов
-- (при помощи переменных пакета и двух триггеров или при помощи COMPAUND-триггера).

-- CREATE OR REPLACE PACKAGE pkg_trigger_control AS
--     FUNCTION is_enabled RETURN BOOLEAN;
--     PROCEDURE disable_trigger;
--     PROCEDURE enable_trigger;
-- END pkg_trigger_control;
-- /
--
-- CREATE OR REPLACE PACKAGE BODY pkg_trigger_control AS
--     g_trigger_enabled BOOLEAN := TRUE;
--
--     FUNCTION is_enabled RETURN BOOLEAN IS
--     BEGIN
--         RETURN g_trigger_enabled;
--     END is_enabled;
--
--     PROCEDURE disable_trigger IS
--     BEGIN
--         g_trigger_enabled := FALSE;
--     END disable_trigger;
--
--     PROCEDURE enable_trigger IS
--     BEGIN
--         g_trigger_enabled := TRUE;
--     END enable_trigger;
-- END pkg_trigger_control;
-- /


--будет мутация
CREATE OR REPLACE TRIGGER trg_bad_client
    AFTER INSERT
    ON client
    FOR EACH ROW
BEGIN
    INSERT INTO client(first_name) VALUES ('Added by trigger');
END;
/

INSERT INTO client (first_name, last_name, birth_date, phone_number) VALUES ('Наталья', 'Захарова', DATE '1998-06-29', '+375292112233');

DROP TRIGGER trg_bad_client;

-- не будет мутации
-- Триггер, который создаёт копию вставленного клиента
-- с уникальным номером телефона и корректным размером имени
CREATE OR REPLACE TRIGGER trg_good_client
    FOR INSERT ON client
    COMPOUND TRIGGER
    TYPE t_client_rec IS RECORD (
                                    first_name   client.first_name%TYPE,
                                    last_name    client.last_name%TYPE,
                                    birth_date   client.birth_date%TYPE,
                                    phone_number client.phone_number%TYPE
                                );

    TYPE t_clients IS TABLE OF t_client_rec;
    g_clients t_clients := t_clients();

AFTER EACH ROW IS
BEGIN
    g_clients.EXTEND;
    g_clients(g_clients.LAST).first_name   := :NEW.first_name;
    g_clients(g_clients.LAST).last_name    := :NEW.last_name;
    g_clients(g_clients.LAST).birth_date   := :NEW.birth_date;
    g_clients(g_clients.LAST).phone_number := :NEW.phone_number;
END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_phone_exists NUMBER;
        v_new_phone    VARCHAR2(13);
    BEGIN
        IF pkg_trigger_control.is_enabled THEN
            pkg_trigger_control.disable_trigger;

            FOR i IN 1 .. g_clients.COUNT LOOP
                    LOOP
                        v_new_phone := '+375' || LPAD(TRUNC(DBMS_RANDOM.VALUE(100000000, 999999999)), 9, '0');

                        SELECT COUNT(*) INTO v_phone_exists
                        FROM client
                        WHERE phone_number = v_new_phone;

                        EXIT WHEN v_phone_exists = 0;
                    END LOOP;

                    INSERT INTO client (first_name, last_name, birth_date, phone_number)
                    VALUES (
                               SUBSTR(g_clients(i).first_name, 1, 3) || ' (copy)',
                               g_clients(i).last_name,
                               g_clients(i).birth_date,
                               v_new_phone
                           );
                END LOOP;

            pkg_trigger_control.enable_trigger;
        END IF;
    END AFTER STATEMENT;
    END trg_good_client;
/


INSERT INTO client (first_name, last_name, birth_date, phone_number)
VALUES ('Ана', 'Бана', DATE '1998-06-29', '+375491236233');

-- Написать триггер INSTEAD OF для работы с не обновляемым представлением, созданным после выполнения п. 2.4 задания к лабораторной работе №3,
-- проверить DML-командами возможность обновления представления после включения триггера (логика работы триггера определяется спецификой предметной области варианта).
CREATE OR REPLACE TRIGGER clients_working_hours_trigger
    INSTEAD OF INSERT OR UPDATE OR DELETE
    ON clients_working_hours_view
DECLARE
    v_current_day  VARCHAR2(20);
    v_current_hour NUMBER;
    v_current_time TIMESTAMP WITH TIME ZONE;
BEGIN
    v_current_time := SYSTIMESTAMP AT TIME ZONE 'Europe/Moscow';
    v_current_day := TO_CHAR(v_current_time, 'DY', 'NLS_DATE_LANGUAGE=RUSSIAN');
    v_current_hour := EXTRACT(HOUR FROM v_current_time);

    IF v_current_day IN ('СБ', 'ВС') THEN
        RAISE_APPLICATION_ERROR(-20001,
                                'Операции разрешены только в рабочие дни (пн–пт). Сегодня: ' || v_current_day);
    END IF;

    IF v_current_hour < 9 OR v_current_hour >= 23 THEN
        RAISE_APPLICATION_ERROR(-20002,
                                'Операции разрешены только с 9:00 до 17:00. Сейчас: ' || v_current_hour || ':00');
    END IF;

    CASE
        WHEN INSERTING THEN INSERT INTO client (id, first_name, last_name, birth_date, phone_number)
                            VALUES (:NEW.id, :NEW.first_name, :NEW.last_name, :NEW.birth_date, :NEW.phone_number);

        WHEN UPDATING THEN UPDATE client
                           SET first_name   = :NEW.first_name,
                               last_name    = :NEW.last_name,
                               birth_date   = :NEW.birth_date,
                               phone_number = :NEW.phone_number
                           WHERE id = :OLD.id;

        WHEN DELETING THEN DELETE FROM client WHERE id = :OLD.id;
        END CASE;
END;
/

INSERT INTO clients_working_hours_view (first_name, last_name, birth_date, phone_number)
VALUES ('Sergey', 'Sidorov', DATE '1995-03-15', '+375297837832');

-- -- Удаление DML триггера для логирования изменений в insurance_contract
-- DROP TRIGGER trg_contract_log;
--
-- -- Удаление DDL триггера
-- DROP TRIGGER trg_ddl_log;
--
-- -- Удаление системных триггеров
-- DROP TRIGGER trg_logon;
-- DROP TRIGGER trg_logoff;
--
-- -- Удаление триггера для бизнес-логики договоров
-- DROP TRIGGER trg_contract_defaults;
--
-- -- Удаление триггера для пеней
-- DROP TRIGGER trg_payment_penalty;
--
-- -- Удаление составного триггера архивации
-- DROP TRIGGER trg_contract_archive;
--
-- -- Удаление проблемного триггера (вызывающего мутацию)
-- DROP TRIGGER trg_bad_client;
--
-- -- Удаление составного триггера для клиентов
-- DROP TRIGGER trg_good_client;
--
-- -- Удаление INSTEAD OF триггера для представления
-- DROP TRIGGER clients_working_hours_trigger;












