-- Написать DML-триггер, регистрирующий изменение данных (вставку, обновление, удаление) в одной из таблиц БД.
-- Во вспомогательную таблицу LOG1 записывать, кто, когда (дата и время) и какое именно изменение произвел,
-- для одного из столбцов сохранять старые и новые значения писать DML-триггер, регистрирующий изменение
-- данных (вставку, обновление, удаление) в одной из таблиц БД. Во вспомогательную таблицу LOG1 записывать,
-- кто, когда (дата и время) и какое именно изменение произвел, для одного из столбцов сохранять старые и новые значения.

CREATE TABLE LOG1
(
    id          INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR2(50),
    operation   VARCHAR2(10),
    user_name   VARCHAR2(50),
    change_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    column_name VARCHAR2(50),
    old_value   VARCHAR2(4000),
    new_value   VARCHAR2(4000)
);

CREATE OR REPLACE TRIGGER trg_contract_log
    AFTER INSERT OR UPDATE OR DELETE
    ON insurance_contract
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO LOG1(table_name, operation, user_name, column_name, new_value)
        VALUES ('INSURANCE_CONTRACT', 'INSERT', USER, 'CONTRACT_STATUS', :NEW.contract_status);
    ELSIF UPDATING THEN
        INSERT INTO LOG1(table_name, operation, user_name, column_name, old_value, new_value)
        VALUES ('INSURANCE_CONTRACT', 'UPDATE', USER, 'CONTRACT_STATUS', :OLD.contract_status, :NEW.contract_status);
    ELSIF DELETING THEN
        INSERT INTO LOG1(table_name, operation, user_name, column_name, old_value)
        VALUES ('INSURANCE_CONTRACT', 'DELETE', USER, 'CONTRACT_STATUS', :OLD.contract_status);
    END IF;
END;
/


-- Написать DDL-триггер, протоколирующий действия пользователей по
-- созданию, изменению и удалению таблиц в схеме во вспомогательную таблицу
-- LOG2 в определенное время и запрещающий эти действия в другое время.
CREATE TABLE LOG2
(
    id          INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_name   VARCHAR2(50),
    operation   VARCHAR2(30),
    object_name VARCHAR2(100),
    log_date    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_ddl_log
    AFTER CREATE OR ALTER OR DROP
    ON SCHEMA
DECLARE
    v_hour NUMBER := TO_NUMBER(TO_CHAR(SYSTIMESTAMP AT TIME ZONE 'Europe/Moscow', 'HH24'));
BEGIN
    IF v_hour BETWEEN 9 AND 17 THEN
        INSERT INTO LOG2(user_name, operation, object_name)
        VALUES (SYS_CONTEXT('USERENV', 'SESSION_USER'), ORA_SYSEVENT, ORA_DICT_OBJ_NAME);
    ELSE
        RAISE_APPLICATION_ERROR(-20030, 'DDL-операции разрешены только с 9 до 17');
    END IF;
END;
/

--Для теста
-- CREATE TABLE test_tbl (
-- id NUMBER
-- );
--
-- -- меняем структуру
-- ALTER TABLE test_tbl ADD name VARCHAR2(100);
--
-- -- удаляем
-- DROP TABLE test_tbl;

-- Написать системный триггер, добавляющий запись во вспомогательную
-- таблицу LOG3, когда пользователь подключается или отключается. В таблицу
-- логов записывается имя пользователя (USER), тип активности (LOGON или LOGOFF),
-- дата (SYSDATE), количество записей в основной таблице БД.

CREATE TABLE LOG3
(
    id           INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_name    VARCHAR2(50),
    activity     VARCHAR2(10),
    log_date     TIMESTAMP DEFAULT SYSTIMESTAMP,
    contract_cnt NUMBER
);

CREATE OR REPLACE TRIGGER trg_logon
    AFTER LOGON
    ON DATABASE
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM insurance_contract;
    INSERT INTO LOG3(user_name, activity, contract_cnt)
    VALUES (USER, 'LOGON', v_cnt);
END;
/

CREATE OR REPLACE TRIGGER trg_logoff
    BEFORE LOGOFF
    ON DATABASE
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM insurance_contract;
    INSERT INTO LOG3(user_name, activity, contract_cnt)
    VALUES (USER, 'LOGOFF', v_cnt);
END;
/

-- Написать триггеры, реализующие бизнес-логику (ограничения) в задан-ной
-- вариантом предметной области. Три задания приведены в прил. 6. Количество
-- и тип триггеров (строковый или операторный, выполняется AFTER или BEFORE)
-- определять самостоятельно исходя из сути заданий и имеющейся схемы БД; учесть,
-- что в некоторых вариантах первые два задания могут быть выполнены в рамках одного триггера,
-- а также возможно возникновение мутации, что приведет к совмещению данного пункта
-- лабораторной работы со сле-дующим. Третий пункт задания предполагает использование
-- планировщика задач, который обязательно должен быть настроен на многократный запуск
-- с использованием частоты, интервала и спецификаторов.

-- 1)При заполнении информации о договоре автоматически вносить текущую дату как начальную, если она не указана агентом,
-- и дату окончания страховки в зависимости от типа и срока страхования, рассчитывать общую стоимость и первоначальный взнос.
-- 2)Следить за суммами выплат, начислять пеню за просроченные выплаты.
-- 3)Переносить в архив старые договора, указывая сумму страховки и выплаты по страховым случаям, если они были.

-- При заполнении информации о договоре автоматически вносить текущую дату как начальную, если она не указана агентом,
-- и дату окончания страховки в зависимости от типа и срока страхования, рассчитывать общую стоимость и первоначальный взнос.
ALTER TABLE insurance_contract
    ADD (
        end_date DATE,
        initial_payment NUMERIC(15, 2)
        );

CREATE OR REPLACE TRIGGER trg_contract_defaults
    BEFORE INSERT
    ON insurance_contract
    FOR EACH ROW
DECLARE
    v_type_name insurance_type.name%TYPE;
    v_coef      NUMBER := 1;
BEGIN
    IF :NEW.contract_date IS NULL THEN
        :NEW.contract_date := SYSDATE;
    END IF;

    :NEW.end_date := :NEW.contract_date + NVL(:NEW.payout_deadline, 365);

    SELECT name
    INTO v_type_name
    FROM insurance_type
    WHERE id = :NEW.insurance_type_id;

    IF v_type_name = 'Жизнь' THEN
        v_coef := 1.5;
    ELSIF v_type_name = 'Авто' THEN
        v_coef := 1.2;
    ELSIF v_type_name = 'Жилье' THEN
        v_coef := 1.3;
    ELSE
        v_coef := 1;
    END IF;

    :NEW.premium := :NEW.premium * v_coef;
    :NEW.initial_payment := :NEW.premium * 0.2;

END;
/


-- 2)Следить за суммами выплат, начислять пеню за просроченные выплаты.
ALTER TABLE payment
    ADD penalty NUMERIC(15, 2);

CREATE OR REPLACE TRIGGER trg_payment_penalty
    BEFORE INSERT OR UPDATE
    ON payment
    FOR EACH ROW
DECLARE
    v_deadline DATE;
BEGIN
    SELECT c.contract_date + c.payout_deadline
    INTO v_deadline
    FROM insurance_contract c
    WHERE c.id = :NEW.insurance_contract_id;

    IF :NEW.payment_date > v_deadline THEN
        :NEW.penalty := (:NEW.amount * 0.01) * (TRUNC(:NEW.payment_date - v_deadline));
    ELSE
        :NEW.penalty := 0;
    END IF;
END;
/

-- 3)Переносить в архив старые договора, указывая сумму страховки и выплаты по страховым случаям, если они были.
CREATE TABLE insurance_contract_archive AS
SELECT *
FROM insurance_contract
WHERE 1 = 0;

ALTER TABLE insurance_contract_archive
    ADD (
        total_payout NUMERIC(15, 2)
        );

CREATE OR REPLACE TRIGGER trg_contract_archive
    AFTER UPDATE OF contract_status
    ON insurance_contract
    FOR EACH ROW
DECLARE
    v_total_payout NUMBER;
BEGIN
    IF :NEW.contract_status = 'Завершен' THEN
        SELECT NVL(SUM(cc.approved_amount), 0)
        INTO v_total_payout
        FROM compensation_claim cc
        WHERE cc.insurance_contract_id = :NEW.id;

        INSERT INTO insurance_contract_archive
        SELECT c.*, v_total_payout
        FROM insurance_contract c
        WHERE c.id = :NEW.id;

        DELETE FROM insurance_contract WHERE id = :NEW.id;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE proc_check_and_archive IS
BEGIN
    UPDATE insurance_contract
    SET contract_status = 'Завершен'
    WHERE contract_status = 'Завершен';

    COMMIT;
END;
/

BEGIN
    DBMS_SCHEDULER.create_job (
            job_name        => 'JOB_TRIGGER_ARCHIVE',
            job_type        => 'STORED_PROCEDURE',
            job_action      => 'PROC_CHECK_AND_ARCHIVE',
            start_date      => SYSTIMESTAMP,
            repeat_interval => 'FREQ=MINUTELY; INTERVAL=10',
            enabled         => TRUE
    );
END;
/

-- Самостоятельно или при помощи преподавателя составить задание на
-- DML триггер, который будет вызывать мутацию таблицы, на которую создан,
-- в случае присутствия в теле триггера команды записи (INSERT INTO, UPDATE, DELETE)
-- в ту же таблицу, и решить эту проблему одним из двух способов
-- (при помощи переменных пакета и двух триггеров или при помощи COMPAUND-триггера).

--будет мутация
CREATE OR REPLACE TRIGGER trg_bad_client
    AFTER INSERT ON client
    FOR EACH ROW
BEGIN
    INSERT INTO client(first_name) VALUES ('Added by trigger');
END;
/


-- не будет мутации
CREATE OR REPLACE TRIGGER trg_good_client
    FOR INSERT ON client
    COMPOUND TRIGGER
    TYPE t_names IS TABLE OF VARCHAR2(100);
    g_names t_names := t_names();

AFTER EACH ROW IS
BEGIN
    g_names.EXTEND;
    g_names(g_names.LAST) := :NEW.first_name || ' (copy)';
END AFTER EACH ROW;

    AFTER STATEMENT IS
    BEGIN
        FOR i IN 1 .. g_names.COUNT LOOP
                INSERT INTO client(first_name) VALUES (g_names(i));
            END LOOP;
    END AFTER STATEMENT;
    END trg_good_client;
/

-- Написать триггер INSTEAD OF для работы с не обновляемым представлением, созданным после выполнения п. 2.4 задания к лабораторной работе №3,
-- проверить DML-командами возможность обновления представления после включения триггера (логика работы триггера определяется спецификой предметной области варианта).
CREATE OR REPLACE TRIGGER clients_working_hours_trigger
    INSTEAD OF INSERT OR UPDATE OR DELETE
    ON clients_working_hours_view
DECLARE
    v_current_day  VARCHAR2(20);
    v_current_hour NUMBER;
    v_current_time TIMESTAMP WITH TIME ZONE;
BEGIN
    v_current_time := SYSTIMESTAMP AT TIME ZONE 'Europe/Moscow';
    v_current_day  := TO_CHAR(v_current_time, 'DY', 'NLS_DATE_LANGUAGE=RUSSIAN');
    v_current_hour := EXTRACT(HOUR FROM v_current_time);

    IF v_current_day IN ('СБ', 'ВС') THEN
        RAISE_APPLICATION_ERROR(-20001,
                                'Операции разрешены только в рабочие дни (пн–пт). Сегодня: ' || v_current_day);
    END IF;

    IF v_current_hour < 9 OR v_current_hour >= 17 THEN
        RAISE_APPLICATION_ERROR(-20002,
                                'Операции разрешены только с 9:00 до 17:00. Сейчас: ' || v_current_hour || ':00');
    END IF;

    CASE
        WHEN INSERTING THEN
            INSERT INTO client (id, first_name, last_name, birth_date, phone_number)
            VALUES (:NEW.id, :NEW.first_name, :NEW.last_name, :NEW.birth_date, :NEW.phone_number);

        WHEN UPDATING THEN
            UPDATE client
            SET first_name   = :NEW.first_name,
                last_name    = :NEW.last_name,
                birth_date   = :NEW.birth_date,
                phone_number = :NEW.phone_number
            WHERE id = :OLD.id;

        WHEN DELETING THEN
            DELETE FROM client WHERE id = :OLD.id;
        END CASE;
END;
/













