CREATE TABLE client
(
    id           INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR2(100) NOT NULL,
    last_name    VARCHAR2(100) NOT NULL,
    birth_date   DATE          NOT NULL,
    phone_number VARCHAR2(13)  NOT NULL
);

CREATE TABLE insurance_type
(
    id         INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255) NOT NULL,
    max_payout NUMERIC(15, 2),
    age_limit  NUMERIC(3)
);

CREATE TABLE agent
(
    id           INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR2(100) NOT NULL,
    last_name    VARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(13)  NOT NULL
);

CREATE TABLE insurance_contract
(
    id                INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    contract_date     DATE         NOT NULL,
    contract_status   VARCHAR2(20) NOT NULL,
    payout_deadline   INTEGER,
    agent_id          INTEGER       NOT NULL,
    client_id         INTEGER       NOT NULL,
    insurance_type_id INTEGER       NOT NULL,
    premium           NUMERIC(15, 2),
    unpaid_premium    NUMERIC(15, 2),

    CONSTRAINT fk_insurance_contract_client FOREIGN KEY (client_id)
        REFERENCES client (id),
    CONSTRAINT fk_insurance_contract_agent FOREIGN KEY (agent_id)
        REFERENCES agent (id),
    CONSTRAINT fk_insurance_contract_type FOREIGN KEY (insurance_type_id)
        REFERENCES insurance_type (id)
);

CREATE TABLE insurance_case
(
    id          INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    description CLOB,
    title       VARCHAR2(255),
    urgency     CHAR(1)
);

CREATE TABLE compensation_claim
(
    id                    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    created_date          DATE   NOT NULL,
    requested_amount      NUMERIC(15, 2),
    approved_amount       NUMERIC(15, 2),
    status                VARCHAR2(50),
    comment_text               CLOB,
    case_id               INTEGER NOT NULL,
    insurance_contract_id INTEGER NOT NULL,
    is_deleted            CHAR(1),

    CONSTRAINT fk_claim_case FOREIGN KEY (case_id)
        REFERENCES insurance_case(id),
    CONSTRAINT fk_claim_contract FOREIGN KEY (insurance_contract_id)
        REFERENCES insurance_contract(id)
);

CREATE TABLE payment
(
    id                    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    amount                NUMERIC(15, 2),
    payment_date          DATE,
    insurance_contract_id INTEGER NOT NULL,

    CONSTRAINT fk_payment_contract FOREIGN KEY (insurance_contract_id)
        REFERENCES insurance_contract (id)
);

--Ограничения
ALTER TABLE client
    ADD CONSTRAINT uq_client_phone UNIQUE (phone_number);

ALTER TABLE client
    ADD CONSTRAINT chk_client_phone_format CHECK (REGEXP_LIKE(phone_number, '^\+375[0-9]{9}$'));

ALTER TABLE insurance_type
    ADD CONSTRAINT chk_insurance_type_payout CHECK (max_payout >= 0);

ALTER TABLE insurance_type
    ADD CONSTRAINT uq_insurance_type_name UNIQUE (name);

ALTER TABLE agent
    ADD CONSTRAINT uq_agent_phone UNIQUE (phone_number);

ALTER TABLE agent
    ADD CONSTRAINT chk_agent_phone_format CHECK (REGEXP_LIKE(phone_number, '^\+375[0-9]{9}$'));

ALTER TABLE insurance_contract
    ADD CONSTRAINT chk_contract_status CHECK (contract_status IN ('Активен', 'Завершён', 'Заморожен'));

ALTER TABLE insurance_contract
    ADD CONSTRAINT chk_contract_premiums CHECK (premium >= 0 AND unpaid_premium >= 0);

ALTER TABLE insurance_case
    ADD CONSTRAINT chk_insurance_case_urgency CHECK (urgency IN ('0', '1'));

ALTER TABLE compensation_claim
    ADD CONSTRAINT chk_claim_amount CHECK (approved_amount <= requested_amount);

ALTER TABLE compensation_claim
    ADD CONSTRAINT chk_claim_deleted CHECK (is_deleted IN ('0', '1'));

ALTER TABLE payment
    ADD CONSTRAINT chk_payment_amount CHECK (amount > 0);

CREATE OR REPLACE TRIGGER trg_check_birth_date
    BEFORE INSERT OR UPDATE ON client
    FOR EACH ROW
BEGIN
    IF :NEW.birth_date >= SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20001, 'Birth date must be in the past');
    END IF;
END;

CREATE OR REPLACE TRIGGER trg_check_contract_date
    BEFORE INSERT OR UPDATE ON insurance_contract
    FOR EACH ROW
BEGIN
    IF :NEW.contract_date > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20002, 'Contract date cannot be in the future');
    END IF;
END;

--Индексы

CREATE INDEX idx_contract_agent ON insurance_contract(agent_id);
CREATE INDEX idx_contract_client ON insurance_contract(client_id);
CREATE INDEX idx_contract_type ON insurance_contract(insurance_type_id);
CREATE INDEX idx_contract_status ON insurance_contract(contract_status);
CREATE INDEX idx_contract_date ON insurance_contract(contract_date);
CREATE INDEX idx_claim_date ON compensation_claim(created_date);

CREATE INDEX idx_payment_contract ON payment(insurance_contract_id);

-- Синонимы
CREATE SYNONYM cl FOR client;
CREATE SYNONYM it FOR insurance_type;
CREATE SYNONYM ag FOR agent;
CREATE SYNONYM ic FOR insurance_contract;
CREATE SYNONYM cs FOR insurance_case;
CREATE SYNONYM cc FOR compensation_claim;
CREATE SYNONYM pay FOR payment;

-- ===== Клиенты =====
INSERT INTO client (first_name, last_name, birth_date, phone_number)
VALUES ('Иван', 'Иванов', DATE '1990-05-15', '+375291234567');
INSERT INTO client (first_name, last_name, birth_date, phone_number)
VALUES ('Петр', 'Петров', DATE '1985-11-20', '+375331112233');
INSERT INTO client (first_name, last_name, birth_date, phone_number)
VALUES ('Ольга', 'Сидорова', DATE '1995-03-10', '+375441234999');
INSERT INTO client (first_name, last_name, birth_date, phone_number)
VALUES ('Мария', 'Коваль', DATE '1978-07-25', '+375251112233');
INSERT INTO client (first_name, last_name, birth_date, phone_number)
VALUES ('Дмитрий', 'Алексеев', DATE '1982-09-14', '+375291119988');

-- ===== Агенты =====
INSERT INTO agent (first_name, last_name, phone_number)
VALUES ('Сергей', 'Сергеев', '+375447778899');
INSERT INTO agent (first_name, last_name, phone_number)
VALUES ('Анна', 'Кузнецова', '+375296661122');
INSERT INTO agent (first_name, last_name, phone_number)
VALUES ('Николай', 'Морозов', '+375333334455');

-- ===== Типы страховок (INSERT ALL) =====

INSERT ALL
    INTO insurance_type (name, max_payout, age_limit) VALUES ('Жизнь', 100000, 65)
SELECT 1 FROM dual;
INSERT ALL
    INTO insurance_type (name, max_payout, age_limit) VALUES ('Авто', 50000, 80)
SELECT 1 FROM dual;
INSERT ALL
    INTO insurance_type (name, max_payout, age_limit) VALUES ('Жилье', 200000, 66)
SELECT 1 FROM dual;
INSERT ALL
    INTO insurance_type (name, max_payout, age_limit) VALUES ('Здоровье', 150000, 70)
SELECT 1 FROM dual;
INSERT ALL
    INTO insurance_type (name, max_payout, age_limit) VALUES ('Путешествия', 75000, 43)
SELECT 1 FROM dual;

-- ===== Страховые контракты =====
INSERT INTO insurance_contract (contract_date, contract_status, payout_deadline, agent_id, client_id, insurance_type_id, premium, unpaid_premium)
VALUES (DATE '2023-01-15', 'Активен', 30, 1, 1, 1, 1500, 0);

INSERT INTO insurance_contract (contract_date, contract_status, payout_deadline, agent_id, client_id, insurance_type_id, premium, unpaid_premium)
VALUES (DATE '2022-10-01', 'Завершён', 60, 2, 2, 2, 2000, 200);

INSERT INTO insurance_contract (contract_date, contract_status, payout_deadline, agent_id, client_id, insurance_type_id, premium, unpaid_premium)
VALUES (DATE '2023-05-10', 'Активен', 45, 3, 3, 3, 5000, 0);

INSERT INTO insurance_contract (contract_date, contract_status, payout_deadline, agent_id, client_id, insurance_type_id, premium, unpaid_premium)
VALUES (DATE '2023-06-20', 'Заморожен', 90, 1, 4, 4, 1200, 600);

INSERT INTO insurance_contract (contract_date, contract_status, payout_deadline, agent_id, client_id, insurance_type_id, premium, unpaid_premium)
VALUES (DATE '2022-08-12', 'Завершён', 30, 2, 5, 5, 1800, 0);

-- ===== Страховые случаи =====
INSERT INTO insurance_case (description, title, urgency)
VALUES ('ДТП с участием легкового автомобиля', 'Дорожное происшествие', '1');
INSERT INTO insurance_case (description, title, urgency)
VALUES ('Пожар в квартире клиента', 'Пожар', '0');
INSERT INTO insurance_case (description, title, urgency)
VALUES ('Сердечный приступ', 'Медицинский случай', '1');
INSERT INTO insurance_case (description, title, urgency)
VALUES ('Повреждение багажа во время поездки', 'Путешествие', '0');

-- ===== Компенсации =====
INSERT INTO compensation_claim (created_date, requested_amount, approved_amount, status, comment_text, case_id, insurance_contract_id, is_deleted)
VALUES (DATE '2023-02-01', 10000, 8000, 'Одобрено', 'Выплата частичная', 1, 2, '0');

INSERT INTO compensation_claim (created_date, requested_amount, approved_amount, status, comment_text, case_id, insurance_contract_id, is_deleted)
VALUES (DATE '2023-03-05', 50000, 50000, 'Одобрено', 'Полная выплата', 2, 1, '0');

INSERT INTO compensation_claim (created_date, requested_amount, approved_amount, status, comment_text, case_id, insurance_contract_id, is_deleted)
VALUES (DATE '2023-07-12', 20000, 0, 'Отклонено', 'Недостаточно доказательств', 3, 3, '0');

INSERT INTO compensation_claim (created_date, requested_amount, approved_amount, status, comment_text, case_id, insurance_contract_id, is_deleted)
VALUES (DATE '2023-09-18', 7500, 7000, 'Одобрено', 'Частичная компенсация', 4, 5, '0');

-- ===== Платежи =====
INSERT INTO payment (amount, payment_date, insurance_contract_id)
VALUES (500, DATE '2023-01-20', 1);
INSERT INTO payment (amount, payment_date, insurance_contract_id)
VALUES (1500, DATE '2022-10-10', 2);
INSERT INTO payment (amount, payment_date, insurance_contract_id)
VALUES (2500, DATE '2023-05-15', 3);
INSERT INTO payment (amount, payment_date, insurance_contract_id)
VALUES (600, DATE '2023-07-01', 4);
INSERT INTO payment (amount, payment_date, insurance_contract_id)
VALUES (1800, DATE '2022-08-20', 5);




